version: '3.8'
services:
  spotify1:
    build:
      context: .
    container_name: spotify1
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.spotify1.rule=Host(`premia-pix.site`)'
      - 'traefik.http.routers.spotify1.entrypoints=websecure'
      - 'traefik.http.services.spotify1.loadbalancer.server.port=3000'
      - 'traefik.http.routers.spotify1.service=spotify1'
      - 'traefik.http.routers.spotify1.tls.certresolver=leresolver'

networks:
  default:
    name: spotify1
    external: true
