version: '3.8'
services:
  premia2:
    build:
      context: .
    container_name: premia2
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.premia2.rule=Host(`app.premia-pix.site`)'
      - 'traefik.http.routers.premia2.entrypoints=websecure'
      - 'traefik.http.services.premia2.loadbalancer.server.port=3000'
      - 'traefik.http.routers.premia2.service=premia2'
      - 'traefik.http.routers.premia2.tls.certresolver=leresolver'

networks:
  default:
    name: premia2
    external: true
