version: '3.8'
services:
  premia1:
    build:
      context: .
      args:
        APP_URL: https://pixpremia.online/
        NEXT_PUBLIC_URLS: https://go.perfectpay.com.br/PPU38COPTO0?
        NEXT_PUBLIC_CHECKOUT: perfectpay
        NEXT_PUBLIC_USER: H
    container_name: premia1
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.premia1.rule=Host(`pixpremia.online`)'
      - 'traefik.http.routers.premia1.entrypoints=websecure'
      - 'traefik.http.services.premia1.loadbalancer.server.port=3000'
      - 'traefik.http.routers.premia1.service=premia1'
      - 'traefik.http.routers.premia1.tls.certresolver=leresolver'

networks:
  default:
    name: premia1
    external: true
