version: '3.8'
services:
  spotify2:
    build:
      context: .
    container_name: spotify2
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.spotify2.rule=Host(`v2.avaliarmusica.site`)'
      - 'traefik.http.routers.spotify2.entrypoints=websecure'
      - 'traefik.http.services.spotify2.loadbalancer.server.port=3000'
      - 'traefik.http.routers.spotify2.service=spotify2'
      - 'traefik.http.routers.spotify2.tls.certresolver=leresolver'

networks:
  default:
    name: spotify2
    external: true
